title: Ploomber Docs
author: Ploomber
copyright: "2024"
logo: static/logo.png

execute:
  execute_notebooks: force

repository:
  url: https://github.com/ploomber/doc
  path_to_book: doc
  branch: main


sphinx:
  config:
    html_theme_options:
      navigation_with_keys: true

    ogp_site_url: https://docs.cloud.ploomber.io/en/latest/

  extra_extensions:
    - sphinxext.opengraph

html:
  favicon: static/favicon.png
  use_issues_button: true
  use_repository_button: true
  announcement: 'Do you need help? <a href="https://ploomber.io/community" target="_blank" rel="noopener noreferrer">Join our Slack!</a>'
  google_analytics_id: G-VR870BDC3T
