# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8501:8501"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./key.pem:/app/key.pem:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
